import uuid
from datetime import datetime

from sqlalchemy.orm import Session

from app.services.review_service import ReviewService


class ExportService:
    @staticmethod
    def export_markdown(db: Session, review_id: uuid.UUID) -> str:
        report = ReviewService.get_review_report(db, review_id)
        if not report:
            return ""

        lines = [
            "# Code Review Report",
            "",
            f"**Review ID:** `{report['review_id']}`  ",
            f"**Overall Score:** {report['overall_score'] or 'N/A'}/10  ",
            f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "---",
            "",
            "## Summary",
            "",
            report.get("summary") or "_No summary available._",
            "",
        ]

        findings = report.get("findings", [])
        if findings:
            lines.append(f"## Findings ({len(findings)})")
            lines.append("")
            lines.append("| # | Severity | Category | File | Line | Message |")
            lines.append("|---|----------|----------|------|------|---------|")
            for i, f in enumerate(findings, 1):
                sev = f.get("severity", "info")
                cat = f.get("category", "")
                file = f.get("file", "")
                line_no = f.get("line", "")
                msg = f.get("message", "").replace("|", "\\|").replace("\n", " ")
                lines.append(f"| {i} | {sev} | {cat} | `{file}` | {line_no} | {msg} |")
            lines.append("")

            for i, f in enumerate(findings, 1):
                suggestion = f.get("suggestion")
                if suggestion:
                    lines.append(f"### Finding {i}: {f.get('category', 'Issue')}")
                    lines.append("")
                    lines.append(f"**File:** `{f.get('file', '')}`:{f.get('line', '')}  ")
                    lines.append(f"**Severity:** {f.get('severity', 'info')}  ")
                    lines.append(f"**Agent:** {f.get('agent', '')}  ")
                    lines.append("")
                    lines.append(f"> {f.get('message', '')}")
                    lines.append("")
                    lines.append(f"**Suggestion:** {suggestion}")
                    lines.append("")

        agent_results = report.get("agent_results", [])
        if agent_results:
            lines.append("## Agent Results")
            lines.append("")
            lines.append("| Agent | Status | Findings | Score |")
            lines.append("|-------|--------|----------|-------|")
            for ar in agent_results:
                score_str = f"{ar['score']:.1f}" if ar.get("score") is not None else "N/A"
                lines.append(f"| {ar['agent_type']} | {ar['status']} | {ar['findings_count']} | {score_str} |")
            lines.append("")

        baseline = report.get("baseline_comparison")
        if baseline:
            lines.append("## Baseline Comparison")
            lines.append("")
            lines.append(f"- Agent findings: {baseline.get('agent_findings_count', 0)}")
            lines.append(f"- Baseline findings: {baseline.get('baseline_findings_count', 0)}")
            lines.append(f"- Unique to agents: {baseline.get('unique_to_agents', 0)}")
            lines.append(f"- Unique to baseline: {baseline.get('unique_to_baseline', 0)}")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by Codalyra-AI*")

        return "\n".join(lines)
