"""add gemini_api_key_encrypted to user

Revision ID: 1b9eff9b8cf8
Revises: fc349d867264
Create Date: 2026-09-04 00:53:01.253818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9eff9b8cf8'
down_revision: Union[str, Sequence[str], None] = 'fc349d867264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gemini_api_key_encrypted')
    # ### end Alembic commands ###
