"""add openai and anthropic api key fields to users

Revision ID: 1fe8f19a7977
Revises: 9912e438a340
Create Date: 2026-09-05 10:54:46.564483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe8f19a7977'
down_revision: Union[str, Sequence[str], None] = '9912e438a340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openai_api_key_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('anthropic_api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anthropic_api_key_encrypted')
    op.drop_column('users', 'openai_api_key_encrypted')
    # ### end Alembic commands ###
