"""add finding_feedback table

Revision ID: 88646d2b56c9
Revises: ef774c2041bf
Create Date: 2026-09-05 16:11:14.898235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88646d2b56c9'
down_revision: Union[str, Sequence[str], None] = 'ef774c2041bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('finding_hash', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'finding_hash', name='uq_finding_feedback')
    )
    op.create_index(op.f('ix_finding_feedback_project_id'), 'finding_feedback', ['project_id'], unique=False)
    op.create_index(op.f('ix_finding_feedback_review_id'), 'finding_feedback', ['review_id'], unique=False)
    op.create_index(op.f('ix_finding_feedback_user_id'), 'finding_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_feedback_user_id'), table_name='finding_feedback')
    op.drop_index(op.f('ix_finding_feedback_review_id'), table_name='finding_feedback')
    op.drop_index(op.f('ix_finding_feedback_project_id'), table_name='finding_feedback')
    op.drop_table('finding_feedback')
    # ### end Alembic commands ###
