"""add provider and model_name to agent_configs

Revision ID: 9912e438a340
Revises: c02c126a60f1
Create Date: 2026-09-05 10:53:26.600908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9912e438a340'
down_revision: Union[str, Sequence[str], None] = 'c02c126a60f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('agent_configs', sa.Column('model_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'model_name')
    op.drop_column('agent_configs', 'provider')
    # ### end Alembic commands ###
