"""add_review_model_and_review_id_fk

Revision ID: bda8004e2d38
Revises: 2ecc38212f50
Create Date: 2026-08-28 22:28:22.298821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda8004e2d38'
down_revision: Union[str, Sequence[str], None] = '2ecc38212f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('pr_title', sa.String(length=500), nullable=True),
    sa.Column('diff_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('baseline_summary', sa.Text(), nullable=True),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_created_by_id'), 'reviews', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_reviews_project_id'), 'reviews', ['project_id'], unique=False)
    op.add_column('runs', sa.Column('review_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_runs_review_id'), 'runs', ['review_id'], unique=False)
    op.create_foreign_key(None, 'runs', 'reviews', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_index(op.f('ix_runs_review_id'), table_name='runs')
    op.drop_column('runs', 'review_id')
    op.drop_index(op.f('ix_reviews_project_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_by_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
