"""add webhook urls to projects

Revision ID: ed30a473ff50
Revises: b8e6db74d8ee
Create Date: 2026-09-05 16:04:56.646221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed30a473ff50'
down_revision: Union[str, Sequence[str], None] = 'b8e6db74d8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('slack_webhook_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('discord_webhook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'discord_webhook_url')
    op.drop_column('projects', 'slack_webhook_url')
    # ### end Alembic commands ###
